### ISSUE TITLE
DirectBuffer exception with HeapByteBufferR

### ISSUE THREAD

**Issue by devinrsmith** [deephacks/lmdbjni#79]
```
Exception in thread "main" java.lang.ClassCastException: java.nio.HeapByteBufferR cannot be cast to sun.nio.ch.DirectBuffer
	at org.fusesource.lmdbjni.DirectBuffer.wrap(DirectBuffer.java:156)
	at org.fusesource.lmdbjni.DirectBuffer.<init>(DirectBuffer.java:119)
```

Pretty easy to see why this is happening.

```
    public final boolean hasArray() {
        return (hb != null) && !isReadOnly;
    }
```

`HeapByteBufferR` is read only, so the call to `hasArray()` is false.

**Comment by krisskross** [comment]
In what context is this happening? Can you provide the complete code?
