### ISSUE TITLE
lmdbjni in AARCH64 platform

### ISSUE THREAD

**Issue by hyunjong** [deephacks/lmdbjni#83]
Hi,

I'm these days trying to run a deep learning framework, CaffeOnSpark, on NVIDIA Jetson TX1 embedded GPU system that is equipped with **64-bit ARM® A57 CPU**. 
When I run a small test program, it stops with the following message. 

//////////////////////////////////////////////message begin//////////////////////////////////
.....
.....
17/02/28 18:50:15 INFO DataSource$: Source data layer:0
17/02/28 18:50:15 INFO LMDB: Batch size:64
17/02/28 18:50:15 INFO DataSource$: Source data layer:1
17/02/28 18:50:15 INFO LMDB: Batch size:100
17/02/28 18:50:15 INFO CaffeOnSpark: interleave
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/ubuntu/CaffeOnSpark/caffe-distri/distribute/lib/liblmdbjni.so: /home/ubuntu/CaffeOnSpark/caffe-distri/distribute/lib/**liblmdbjni.so**: cannot open shared object file: No such file or directory (**Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform**)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.yahoo.ml.caffe.LmdbRDD$.com$yahoo$ml$caffe$LmdbRDD$$loadLibrary(LmdbRDD.scala:244)
        at com.yahoo.ml.caffe.LmdbRDD.com$yahoo$ml$caffe$LmdbRDD$$openDB(LmdbRDD.scala:198)
        at com.yahoo.ml.caffe.LmdbRDD.getPartitions(LmdbRDD.scala:45)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1911)
        at org.apache.spark.rdd.RDD.count(RDD.scala:1115)
        at com.yahoo.ml.caffe.CaffeOnSpark.trainWithValidation(CaffeOnSpark.scala:257)
        at com.yahoo.ml.caffe.CaffeOnSpark$.main(CaffeOnSpark.scala:42)
        at com.yahoo.ml.caffe.CaffeOnSpark.main(CaffeOnSpark.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
...
...
//////////////////////////////////////////////message end//////////////////////////////////

CaffeOnSpark is distributed with prebuilt liblmdbjni.so
To make my own liblmdbjni.so file, I tried to clone lmdbjni from https://github.com/deephacks/lmdbjni, build, extract liblmdbjni.so file from the jar file, and then make use of the new liblmdbjni.so file to run the same test, but it failed with the same reason error message. 
readelf clearly shows the library build for X86-64 architecture as shown below. **Is there any way to build obtain liblmdbjni.so file for aarch64 architecture**?

//////////////////////////////////////////////message begin//////////////////////////////////
ubuntu@lab:~$ readelf -a /home/ubuntu/CaffeOnSpark/caffe-distri/distribute/lib/liblmdbjni.so | more
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x1ef50
  Start of program headers:          64 (bytes into file)
  Start of section headers:          1628656 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         6
  Size of section headers:           64 (bytes)
  Number of section headers:         37
  Section header string table index: 34
...
...
//////////////////////////////////////////////message end//////////////////////////////////

**Comment by krisskross** [comment]
There are build instructions on the wiki. Try replacing the JAR instead to the .so file. The .so file is unpacked to /tmp as lmdbjni is loaded.

**Comment by hyunjong** [comment]
@krisskross Thanks. I solved the problem. 
For those who might have the same issue later on, I first built hawtjni first with one of its header file modified as shown in the link below. Then I changed the pom.xml file to match the hawtjni's version definition in the file to the version of hawtjni I installed earelier.
https://github.com/fusesource/hawtjni/issues/18

**Comment by krisskross** [comment]
Glad to hear that. Thanks for sharing!
