### ISSUE TITLE
Permission denied when opening DB with RDONLY flag

### ISSUE THREAD

**Issue by unoexperto** [deephacks/lmdbjni#87]
Guys, could you please suggest why I'm getting 

```
Exception in thread "main" org.fusesource.lmdbjni.LMDBException: Permission denied
	at org.fusesource.lmdbjni.Util.checkErrorCode(Util.java:44)
	at org.fusesource.lmdbjni.Env.createTransaction(Env.java:451)
	at org.fusesource.lmdbjni.Env.createWriteTransaction(Env.java:409)
	at org.fusesource.lmdbjni.Env.openDatabase(Env.java:541)
```

when I open DB as 

`env.open("/home/zzz/lmdb/", org.fusesource.lmdbjni.Constants.RDONLY)`

?

I'm on Linux Mint 18. Same DB get opened fine with `lmdbjava`.

**Comment by krisskross** [comment]
You're opening a write transaction on a read only database.
